apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: maven-web-app
  template:
    metadata:
      labels:
        app: maven-web-app
    spec:
      containers:
      - name: maven-web-app
        image: hemalatha777/dockermavenimage:1776437729
        ports:
        - containerPort: 80

